---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  require_chef_omnibus: true
  remove_images: true

provisioner: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    image:            ubuntu-upstart
    disable_upstart:  false
    run_command:      /sbin/init

suites:
- name: default
  run_list:
    - "recipe[nginx_passenger]"
    - "recipe[nginx_passenger-test]"
  attributes:
    nginx_passenger:
      sites_dir:  "/etc/nginx/sites"
      log_dir:    "/var/log/nginx-sites"
